version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - nestnetwork
  test-postgres:
    image: postgres:13
    container_name: testpostgres13
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - nestnetwork
networks:
  nestnetwork: